export enum USER_TAG {
  USER = "USER",
  AUTH = "AUTH",
  LOGIN = "LOGIN",
  CONFIRM_OTP = "CONFIRM_OTP",
  USER_LIST = "USER_LIST",
  INVITE = "INVITE",
  ACCEPT_INVITATION = "ACCEPT_INVITATION",
  USER_INVITATION_LIST = "USER_INVITATION_LIST",
  USER_SUMMARY = "USER_SUMMARY",
}

export enum SUBSCRIPTION_TAG {
  SUBSCRIPTION = "SUBSCRIPTION",
  INTENT = "INTENT",
  SECRET = "SECRET",
}
export enum PRODUCT_TAG {
  PRODUCT = "PRODUCT",
}
export enum AUTH_TAG {
  AUTH = "AUTH",
}
export enum WORKSPACE_TAG {
  WORKSPACE = "WORKSPACE",
}

export enum PAYMENT_TAG {
  PAYMENT = "PAYMENT",
}

export enum CABINET_TAG {
  CABINET = "CABINET",
  CABINET_LIST = "CABINET_LIST",
  CABINET_SUMMARY = "CABINET_SUMMARY",
}

export enum PATIENT_TAG {
  PATIENT = "PATIENT",
  PATIENT_LIST = "PATIENT_LIST",
  PATIENT_RECORD = "PATIENT_RECORD",
  PATIENT_SUMMARY = "PATIENT_SUMMARY",
}

export enum DENTAL_MAP_TAG {
  DENTAL_MAP_RECORD = "DENTAL_MAP_RECORD",
}
export enum APPOINTMENT_TAG {
  APPOINTMENT_LIST = "APPOINTMENT_LIST",
}
export enum CHAIR_TAG {
  CHAIR_SUMMARY = "CHAIR_SUMMARY",
}

export enum REDUCER {
  USER = "USER",
  AUTH = "AUTH",
  PRODUCT = "PRODUCT",
  WORKSPACE = "WORKSPACE",
  SUBSCRIPTION = "SUBSCRIPTION",
  PAYMENT = "PAYMENT",
  CABINET = "CABINET",
  PATIENT = "PATIENT",
  DENTAL_MAP = "DENTAL_MAP",
  APPOINTMENT = "APPOINTMENT",
  CHAIR = "CHAIR",
}

export enum CACHE_KEYS {
  LOGIN = "LOGIN",
}
