export enum TAG {
  USER = "USER",
  CONFIRM_OTP = "CONFIRM_OTP",
  AUTH = "AUTH",
  LOGIN = "LOGIN",
  PRODUCT = "PRODUCT",
  WORKSPACE = "WORKSPACE",
  SUBSCRIPTION = "SUBSCRIPTION",
  INTENT = "INTENT",
}

export enum REDUCER {
  USER = "USER",
  AUTH = "AUTH",
  PRODUCT = "PRODUCT",
  WORKSPACE = "WORKSPACE",
  SUBSCRIPTION = "SUBSCRIPTION",
}

export enum CACHE_KEYS {
  LOGIN = "LOGIN",
}
