export enum USER_TAG {
  USER = "USER",
  AUTH = "AUTH",
  LOGIN = "LOGIN",
  CONFIRM_OTP = "CONFIRM_OTP",
}

export enum SUBSCRIPTION_TAG {
  SUBSCRIPTION = "SUBSCRIPTION",
  INTENT = "INTENT",
  SECRET = "SECRET",
}
export enum PRODUCT_TAG {
  PRODUCT = "PRODUCT",
}
export enum AUTH_TAG {
  AUTH = "AUTH",
}
export enum WORKSPACE_TAG {
  WORKSPACE = "WORKSPACE",
}

export enum REDUCER {
  USER = "USER",
  AUTH = "AUTH",
  PRODUCT = "PRODUCT",
  WORKSPACE = "WORKSPACE",
  SUBSCRIPTION = "SUBSCRIPTION",
}

export enum CACHE_KEYS {
  LOGIN = "LOGIN",
}
